# Generated by Django 2.0.5 on 2018-05-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vodel', models.FileField(upload_to='media')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
