# Generated by Django 2.0.5 on 2018-05-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='name',
        ),
        migrations.AddField(
            model_name='img',
            name='image_address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='img',
            name='vodel_address',
            field=models.CharField(default='', max_length=20),
        ),
    ]
