# Generated by Django 2.0.5 on 2018-05-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180524_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosbucket',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='img',
            name='sign',
        ),
    ]
